server:
  port: 8080

spring:
  config:
    import: optional:configserver://localhost:8888
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id : estudiantes
          uri : http://localhost:8090
          predicates:
            - Path=/api/estudiante/**